# Generated by Django 3.2 on 2021-08-27 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Minimum length of 5 characters', regex='^.{5}$')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='nomatch', message='Minimum length of 3 characters', regex='^.{3}$')]),
        ),
    ]
